---
services:
  app:
    container_name: homey
    build:
      context: .
    image: homey:task
    command: bundle exec ./bin/rails server -b 0.0.0.0
    environment:
      - RAILS_ENV
      - RAILS_MASTER_KEY
      - RAILS_LOG_TO_STDOUT=true
    ports:
      - 3000:3000
    volumes:
      - .:/rails
    restart: on-failure
    tty: true
    stdin_open: true
    healthcheck:
      test: curl --fail http://localhost:3000/up || exit 1    
